#!/usr/bin/env bash
# Autogenerated by LiteX / git: 863a2b14f
set -e -u -x -o pipefail

quartus_map --read_settings_files=on  --write_settings_files=off terasic_de0nano_propio_pl -c terasic_de0nano_propio_pl
quartus_fit --read_settings_files=off --write_settings_files=off terasic_de0nano_propio_pl -c terasic_de0nano_propio_pl
quartus_asm --read_settings_files=off --write_settings_files=off terasic_de0nano_propio_pl -c terasic_de0nano_propio_pl
quartus_sta terasic_de0nano_propio_pl -c terasic_de0nano_propio_pl
if [ -f "terasic_de0nano_propio_pl.sof" ]
then
    quartus_cpf -c terasic_de0nano_propio_pl.sof terasic_de0nano_propio_pl.rbf
fi

if [ -f "terasic_de0nano_propio_pl.sof" ]
then
    quartus_cpf -c -q "12.0MHz" -g 3.3 -n p terasic_de0nano_propio_pl.sof terasic_de0nano_propio_pl.svf
fi
